/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion;

import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import org.itson.utils.Render;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.itson.daos.PersonaDAO;
import org.itson.dominio.ParametrosBusquedaPersonas;
import org.itson.dominio.Persona;
import org.itson.excepciones.PersistenciaException;
import org.itson.interfaces.IPersonaDAO;
import org.itson.utils.ConfiguracionPaginado;

/**
 *Clase que contiene la pantalla que consulta las personas para luego consultar sus trámites
 * @author Hugo Navarro (233470)/Jorge Sánchez(233012)
 */
public class ConsultaTramites1Form extends javax.swing.JFrame {

    private final ConfiguracionPaginado configPaginado;
    IPersonaDAO dao = new PersonaDAO();

    /**
     * Constructor que crea un ConsultaTramtes1Form, configura la tabla para poder asignarle un boton
     * y configura el páginado que tendrá la tabla
     */
    public ConsultaTramites1Form() {
        initComponents();
        this.tblPersonas.setDefaultRenderer(Object.class, new Render());
        this.configPaginado = new ConfiguracionPaginado(0, 3);
        ParametrosBusquedaPersonas parametros;
    }

    /**
     * Método que carga la tabla de datos dependiendo de los parametros obtenidos para filtrar la busqueda
     * @param parametros filtros que se aplicaran a la consulta de personas
     */
    public void cargarTabla(ParametrosBusquedaPersonas parametros) {
        this.tblPersonas.setDefaultRenderer(Object.class, new Render());
        JButton btnSeleccionar = new JButton("Seleccionar");
        btnSeleccionar.setName("select");
        DefaultTableModel modelo = (DefaultTableModel) this.tblPersonas.getModel();
        modelo.setRowCount(0);
        List<Persona> personasBusqueda = dao.consultarPersonas(parametros, configPaginado);

        for (Persona personaEn : personasBusqueda) {
            Object[] fila = {personaEn.getRfc(), personaEn.getNombres() + " " + personaEn.getApellidoPaterno() + " " + personaEn.getApellidoMaterno(), personaEn.getFechaNacimiento(), btnSeleccionar};
            modelo.addRow(fila);
        }
        this.tblPersonas.setModel(modelo);

    }

    /**
     * Método que hace que se avance la página de la tabla
     * @param parametros se necesita para cargar la tabla
     */
    private void avanzarPagina(ParametrosBusquedaPersonas parametros) {
        this.configPaginado.avanzarPagina();
        this.cargarTabla(parametros);
    }

    /**
     * Método que hace que se retroceda la página 
     * @param parametros se necesita para cargar la tabla
     */
    private void retrocederPagina(ParametrosBusquedaPersonas parametros) {
        this.configPaginado.retrocederPagina();
        this.cargarTabla(parametros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfRfc = new javax.swing.JTextField();
        txtfNombre = new javax.swing.JTextField();
        txtfAnioNac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        cbxElementosPágina = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Consultar trámites");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("RFC");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Año de nacimiento");

        txtfRfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfRfcKeyTyped(evt);
            }
        });

        txtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfNombreKeyTyped(evt);
            }
        });

        txtfAnioNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfAnioNacKeyTyped(evt);
            }
        });

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFC", "Nombre", "Fecha Nacimiento", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersonas);
        if (tblPersonas.getColumnModel().getColumnCount() > 0) {
            tblPersonas.getColumnModel().getColumn(0).setResizable(false);
            tblPersonas.getColumnModel().getColumn(1).setResizable(false);
            tblPersonas.getColumnModel().getColumn(2).setResizable(false);
            tblPersonas.getColumnModel().getColumn(3).setResizable(false);
        }

        btnConsultar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnMenu.setText("Regresar al menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnAvanzar.setText("---->");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        btnRetroceder.setText("<----");
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });

        cbxElementosPágina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "5", "10" }));
        cbxElementosPágina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxElementosPáginaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfRfc)
                    .addComponent(txtfNombre)
                    .addComponent(txtfAnioNac, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnMenu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnRetroceder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxElementosPágina, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(btnAvanzar)))
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfAnioNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvanzar)
                    .addComponent(btnRetroceder)
                    .addComponent(cbxElementosPágina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que te manda de regreso al menú principal
     * @param evt evento que desencadena la acción 
     */
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        MenuForm mf = new MenuForm();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * Acción que consulta las personas
     * @param evt evento que desencadena la acción 
     */
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String rfc = this.txtfRfc.getText();
        String nombre = this.txtfNombre.getText();
        Integer anioNac;
        if (this.txtfAnioNac.getText().equals("")) {
            anioNac = null;
        } else {
            anioNac = Integer.valueOf(this.txtfAnioNac.getText());
        }
        if (rfc.equals("") && nombre.equals("") && anioNac == null) {

            JOptionPane.showMessageDialog(null, "Ingresa al menos un campo para consultar.", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
        ParametrosBusquedaPersonas parametros = new ParametrosBusquedaPersonas(rfc, nombre, anioNac);

        this.cargarTabla(parametros);

    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * Método que hace que puedas hacer click en el botón generado en la columna final de la tabla
     * y te manda al siguiente formulario
     * @param evt evento que desencadena la acción 
     */
    private void tblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonasMouseClicked
        int column = this.tblPersonas.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / this.tblPersonas.getRowHeight();

        if (row < this.tblPersonas.getRowCount() && row >= 0 && column < this.tblPersonas.getColumnCount()
                && column >= 0) {
            Object value = this.tblPersonas.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                String rfc = this.tblPersonas.getValueAt(0, 0).toString();
                try {
                    System.out.println("Hola soy goku");
                    System.out.println(rfc);
                    ConsultaTramites2Form ctf = new ConsultaTramites2Form(rfc);
                    ctf.setVisible(true);
                    this.dispose();

                } catch (PersistenciaException ex) {
                    Logger.getLogger(ConsultaTramites1Form.class
                            .getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_tblPersonasMouseClicked

    /**
     * Acción que te hace avanzar el paginado de la tabla
     * @param evt evento que desencadena la acción 
     */
    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        String rfc = this.txtfRfc.getText();
        String nombre = this.txtfNombre.getText();
        Integer anioNac;
        if (this.txtfAnioNac.getText().equals("")) {
            anioNac = null;
        } else {
            anioNac = Integer.valueOf(this.txtfAnioNac.getText());
        }
        ParametrosBusquedaPersonas parametros = new ParametrosBusquedaPersonas(rfc, nombre, anioNac);
        avanzarPagina(parametros);
    }//GEN-LAST:event_btnAvanzarActionPerformed

     /**
     * Acción que hace retroceder el paginado de la tabla
     * @param evt evento que desencadena la acción
     */
    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        String rfc = this.txtfRfc.getText();
        String nombre = this.txtfNombre.getText();
        Integer anioNac;
        if (this.txtfAnioNac.getText().equals("")) {
            anioNac = null;
        } else {
            anioNac = Integer.valueOf(this.txtfAnioNac.getText());
        }
        ParametrosBusquedaPersonas parametros = new ParametrosBusquedaPersonas(rfc, nombre, anioNac);

        retrocederPagina(parametros);
    }//GEN-LAST:event_btnRetrocederActionPerformed

   /**
     * Acción que revisa si cambio un elemento de la combobox y te lleva a esa pagina
     * @param evt evento que desencadena la acción
     */
    private void cbxElementosPáginaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxElementosPáginaItemStateChanged
        String rfc = this.txtfRfc.getText();
        String nombre = this.txtfNombre.getText();
        Integer anioNac;
        if (this.txtfAnioNac.getText().equals("")) {
            anioNac = null;
        } else {
            anioNac = Integer.valueOf(this.txtfAnioNac.getText());
        }
        ParametrosBusquedaPersonas parametros = new ParametrosBusquedaPersonas(rfc, nombre, anioNac);
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int elementoPorPagina = Integer.parseInt(evt.getItem().toString());
            this.configPaginado.setElementosPagina(elementoPorPagina);
            this.cargarTabla(parametros);
        }
    }//GEN-LAST:event_cbxElementosPáginaItemStateChanged

    /**
     * Evento que hace que no se puedan ingresar espacios y que las letras que se ingrenen en el campo
     * de texto se hagan mayúsculas en el campo de texto de rfc
     * @param evt evento que desencadena la acción 
     */
    private void txtfRfcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfRfcKeyTyped
        if (txtfRfc.getText().length() >= 50) {
            evt.consume();
        }
        final char keyChar = evt.getKeyChar();
        if (!(Character.isLetterOrDigit(keyChar) || (keyChar == KeyEvent.VK_BACK_SPACE) || keyChar == KeyEvent.VK_DELETE)) {
            evt.consume();
        } else if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_txtfRfcKeyTyped

    /**
     * Evento que hace que no se puedan ingresar espacios y que las letras que se ingrenen en el campo
     * de texto se hagan mayúsculas en el campo de texto de nombre
     * @param evt evento que desencadena la acción 
     */
    private void txtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfNombreKeyTyped
        // TODO add your handling code here
        if (txtfNombre.getText().length() >= 50) {
            evt.consume();
        }
        final char keyChar = evt.getKeyChar();
        if (!(Character.isLetter(keyChar) || (keyChar == KeyEvent.VK_BACK_SPACE) || keyChar == KeyEvent.VK_DELETE || Character.isWhitespace(keyChar))) {
            evt.consume();
        } else if (Character.isLowerCase(keyChar)) {
            evt.setKeyChar((keyChar));
        }
    }//GEN-LAST:event_txtfNombreKeyTyped

    /**
     * Evento que hace que no se puedan ingresar espacios y que solamente se puedan ingresar números, 
     * además de limitarlo a solo 4 digitos
     * @param evt evento que desencadena la acción 
     */
    private void txtfAnioNacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfAnioNacKeyTyped
        // TODO add your handling code here:
        if (txtfAnioNac.getText().length() >= 4) {
            evt.consume();
        }
        final char keyChar = evt.getKeyChar();
        if (!(Character.isDigit(keyChar) || (keyChar == KeyEvent.VK_BACK_SPACE) || keyChar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtfAnioNacKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JComboBox<String> cbxElementosPágina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtfAnioNac;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfRfc;
    // End of variables declaration//GEN-END:variables
}
