/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.presentacion;

import org.itson.daos.PersonaDAO;
import org.itson.interfaces.IPersonaDAO;

/**
 *Clase que contiene la pantalla del menú principal
 * @author Hugo Navarro (233470)/Jorge Sánchez(233012)
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTramiteLicencia = new javax.swing.JButton();
        btnTramitePlacas = new javax.swing.JButton();
        btnReporteTramites = new javax.swing.JButton();
        btnConsutaTramites = new javax.swing.JButton();
        btnInsercion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lulutenencia");

        btnTramiteLicencia.setBackground(new java.awt.Color(255, 255, 255));
        btnTramiteLicencia.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnTramiteLicencia.setForeground(new java.awt.Color(0, 0, 0));
        btnTramiteLicencia.setText("Tramitar licencia");
        btnTramiteLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramiteLicenciaActionPerformed(evt);
            }
        });

        btnTramitePlacas.setBackground(new java.awt.Color(255, 255, 255));
        btnTramitePlacas.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnTramitePlacas.setForeground(new java.awt.Color(0, 0, 0));
        btnTramitePlacas.setText("Tramitar placa");
        btnTramitePlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitePlacasActionPerformed(evt);
            }
        });

        btnReporteTramites.setBackground(new java.awt.Color(255, 255, 255));
        btnReporteTramites.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnReporteTramites.setForeground(new java.awt.Color(0, 0, 0));
        btnReporteTramites.setText("Reporte de tramites");
        btnReporteTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteTramitesActionPerformed(evt);
            }
        });

        btnConsutaTramites.setBackground(new java.awt.Color(255, 255, 255));
        btnConsutaTramites.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnConsutaTramites.setForeground(new java.awt.Color(0, 0, 0));
        btnConsutaTramites.setText("Consultar tramites");
        btnConsutaTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsutaTramitesActionPerformed(evt);
            }
        });

        btnInsercion.setText("Inserción masiva de personas");
        btnInsercion.setBackground(new java.awt.Color(255, 255, 255));
        btnInsercion.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnInsercion.setForeground(new java.awt.Color(0, 0, 0));
        btnInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsercionActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnInsercion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnTramiteLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReporteTramites)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTramitePlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsutaTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTramiteLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTramitePlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsutaTramites, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsercion)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acción que te manda para tramitar licencias
     * @param evt evento que desencadena la acción
     */
    private void btnTramiteLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramiteLicenciaActionPerformed
        LicenciaForm lf = new LicenciaForm();
        lf.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTramiteLicenciaActionPerformed

    /**
     * Acción que te inserta las 20 personas para la prueba
     * @param evt evento que desencadena la acción
     */
    private void btnInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionActionPerformed
        IPersonaDAO ip = new PersonaDAO();
        ip.insertarPersonas();
    }//GEN-LAST:event_btnInsercionActionPerformed

    /**
     *Acción que cierra el programa
     * @param evt evento que desencadena la acción
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * Acción que te lleva al registro de placas
     * @param evt evento que desencadena la acción
     */
    private void btnTramitePlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitePlacasActionPerformed
        PlacaForm pf = new PlacaForm();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTramitePlacasActionPerformed

    /**
     * Acción que te lleva a la consulta de tramites
     * @param evt evento que desencadena la acción
     */
    private void btnConsutaTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutaTramitesActionPerformed
        ConsultaTramites1Form ct1 = new ConsultaTramites1Form();
        ct1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsutaTramitesActionPerformed

    /**
     * Acción que te lleva al reporte de los tramites
     * @param evt evento que desencadena la acción
     */
    private void btnReporteTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteTramitesActionPerformed
        ReporteForm reporte = new ReporteForm();
        reporte.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReporteTramitesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsutaTramites;
    private javax.swing.JButton btnInsercion;
    private javax.swing.JButton btnReporteTramites;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTramiteLicencia;
    private javax.swing.JButton btnTramitePlacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
